# Generated by Django 2.2.6 on 2021-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210820_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Создайте название группы', max_length=200, verbose_name='Название группы'),
        ),
    ]
