# Generated by Django 2.2.16 on 2021-08-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210820_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Поле ввода текста', verbose_name='Текст'),
        ),
    ]
