# Generated by Django 2.2.16 on 2021-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210904_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение, которое относится к посту', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
